version: "3"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped          
